[general]
lunarEventChance = 0.4
[events]
bloodMoonWeight = 60
crimsonMoonWeight = 20
minerMoonWeight = 40
whiteMoonWeight = 10
tinyMoonWeight = 0
bigMoonWeight = 0
badOmenMoonWeight = 5
heroMoonWeight = 5
eclipseMoonWeight = 2
[crimson]
crimsonReplacements = ["minecraft:zombie,minecraft:zombified_piglin", "minecraft:husk,minecraft:zombified_piglin", "minecraft:drowned,minecraft:zombified_piglin", "minecraft:skeleton,minecraft:wither_skeleton", "minecraft:creeper,minecraft:ghast", "minecraft:slime,minecraft:magma_cube", "minecraft:spider,minecraft:zoglin"]
