version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
eternal_starlight = true
paladins = true
endrem = true
easymagic = true
friendsandfoes = true
galosphere = true
rogues = true
runes = true
another_furniture = true
easyanvils = true
visualworkbench = true
sereneseasons = true
minecraft = true
gobber2 = true
travelersbackpack = true
jewelry = true
waystones = true
archers = true
chunkloaders = true
advancednetherite = true
spell_engine = true
enchantinginfuser = true
toms_storage = true
knightlib = true
waterframes = true
